//
// ChatSessionLastViewedByInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatSessionLastViewedByInner: Codable, JSONEncodable, Hashable {

    static let userIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[\\w\\-\\|]+$/")
    public var userId: String?
    public var lastViewedAt: Date?

    public init(userId: String? = nil, lastViewedAt: Date? = nil) {
        self.userId = userId
        self.lastViewedAt = lastViewedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case lastViewedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(lastViewedAt, forKey: .lastViewedAt)
    }
}

