//
// Education.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Education: String, Codable, CaseIterable {
    case ged = "GED"
    case associates = "ASSOCIATES"
    case bachelors = "BACHELORS"
    case masters = "MASTERS"
    case phd = "PHD"
    case notDisclosed = "NOT_DISCLOSED"
}
