//
// Ethnicity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * AMERICAN_INDIAN - A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent * BLACK - A person having origins in any of the black racial groups of Africa * EAST_ASIAN - A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent * HISPANIC - A person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin * MIDDLE_EASTERN - For example Egypt * PACIFIC_ISLANDER - A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands. * SOUTH_ASIAN - For example India * WHITE - A person having origins in any of the original peoples of Europe, the Middle East, or North Africa * NOT_DISCLOSED  */
public enum Ethnicity: String, Codable, CaseIterable {
    case americanIndian = "AMERICAN_INDIAN"
    case black = "BLACK"
    case eastAsian = "EAST_ASIAN"
    case hispanic = "HISPANIC"
    case middleEastern = "MIDDLE_EASTERN"
    case pacificIslander = "PACIFIC_ISLANDER"
    case southAsian = "SOUTH_ASIAN"
    case white = "WHITE"
    case notDisclosed = "NOT_DISCLOSED"
}
