//
// ExpenseRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cost of the date:  * FREE  | no cost  * $     | &lt; $20  * $$    | $20 - $40  * $$$   | $40 - $100  * $$$$  | &gt; $100  */
public enum ExpenseRating: String, Codable, CaseIterable {
    case free = "FREE"
    case dollar = "$"
    case dollarDollar = "$$"
    case dollarDollarDollar = "$$$"
    case dollarDollarDollarDollar = "$$$$"
}
