//
// HealthStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum HealthStatus: String, Codable, CaseIterable {
    case healthy = "HEALTHY"
    case warning = "WARNING"
    case degraded = "DEGRADED"
}
