//
// HealthStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The api health status for each environment */
public struct HealthStatusResponse: Codable, JSONEncodable, Hashable {

    public var devEnv: HealthStatusResponseDevEnv?
    public var stagingEnv: HealthStatusResponseDevEnv?
    public var prodEnv: HealthStatusResponseDevEnv?

    public init(devEnv: HealthStatusResponseDevEnv? = nil, stagingEnv: HealthStatusResponseDevEnv? = nil, prodEnv: HealthStatusResponseDevEnv? = nil) {
        self.devEnv = devEnv
        self.stagingEnv = stagingEnv
        self.prodEnv = prodEnv
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case devEnv
        case stagingEnv
        case prodEnv
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(devEnv, forKey: .devEnv)
        try container.encodeIfPresent(stagingEnv, forKey: .stagingEnv)
        try container.encodeIfPresent(prodEnv, forKey: .prodEnv)
    }
}

