//
// HealthStatusResponseDevEnv.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthStatusResponseDevEnv: Codable, JSONEncodable, Hashable {

    public var status: HealthStatus?
    public var updatedAt: Date?
    public var downtimeEndEstimate: Date?

    public init(status: HealthStatus? = nil, updatedAt: Date? = nil, downtimeEndEstimate: Date? = nil) {
        self.status = status
        self.updatedAt = updatedAt
        self.downtimeEndEstimate = downtimeEndEstimate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case updatedAt
        case downtimeEndEstimate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(downtimeEndEstimate, forKey: .downtimeEndEstimate)
    }
}

