//
// LocationIndicatorDistanceFromSearchLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LocationIndicatorDistanceFromSearchLocation: Codable, JSONEncodable, Hashable {

    public enum Unit: String, Codable, CaseIterable {
        case meters = "METERS"
    }
    public var length: Double?
    public var unit: Unit?

    public init(length: Double? = nil, unit: Unit? = nil) {
        self.length = length
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case length
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

