//
// MarketingChannels.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MarketingChannels: String, Codable, CaseIterable {
    case emailNewsletter = "EMAIL_NEWSLETTER"
    case newsArticle = "NEWS_ARTICLE"
    case podcast = "PODCAST"
    case searchEngine = "SEARCH_ENGINE"
    case socialMediaPost = "SOCIAL_MEDIA_POST"
    case socialMediaAd = "SOCIAL_MEDIA_AD"
    case website = "WEBSITE"
    case wordOfMouth = "WORD_OF_MOUTH"
    case other = "OTHER"
}
