//
// NotificationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum NotificationType: String, Codable, CaseIterable {
    case chatSupportAnnouncement = "CHAT_SUPPORT_ANNOUNCEMENT"
    case chatRequest = "CHAT_REQUEST"
    case chatNewReply = "CHAT_NEW_REPLY"
    case discoverRefresh = "DISCOVER_REFRESH"
    case troovCancelled = "TROOV_CANCELLED"
    case troovConfirmed = "TROOV_CONFIRMED"
    case troovJoinRequestCancelled = "TROOV_JOIN_REQUEST_CANCELLED"
    case troovNewJoinRequest = "TROOV_NEW_JOIN_REQUEST"
    case troovStartTimeChanged = "TROOV_START_TIME_CHANGED"
}
