//
// PaginationOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PaginationOrder: String, Codable, CaseIterable {
    case distance = "DISTANCE"
    case startTime = "START_TIME"
}
