//
// PhoneNumber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** a user phone number */
public struct PhoneNumber: Codable, JSONEncodable, Hashable {

    static let localNumberRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^\\d{1,12}$/")
    public var countryName: CountryName?
    public var countryCode: CountryCode?
    public var countryPhoneCode: CountryPhoneCode?
    public var localNumber: String?

    public init(countryName: CountryName? = nil, countryCode: CountryCode? = nil, countryPhoneCode: CountryPhoneCode? = nil, localNumber: String? = nil) {
        self.countryName = countryName
        self.countryCode = countryCode
        self.countryPhoneCode = countryPhoneCode
        self.localNumber = localNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case countryName
        case countryCode
        case countryPhoneCode
        case localNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(countryName, forKey: .countryName)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(countryPhoneCode, forKey: .countryPhoneCode)
        try container.encodeIfPresent(localNumber, forKey: .localNumber)
    }
}

