//
// PoliticalAffiliation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PoliticalAffiliation: String, Codable, CaseIterable {
    case liberal = "LIBERAL"
    case moderate = "MODERATE"
    case conservative = "CONSERVATIVE"
    case apolitical = "APOLITICAL"
    case notDisclosed = "NOT_DISCLOSED"
}
