//
// ProfileFilterAttributesMinHeight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProfileFilterAttributesMinHeight: Codable, JSONEncodable, Hashable {

    public enum Unit: String, Codable, CaseIterable {
        case _in = "IN"
        case cm = "CM"
    }
    public var length: Int?
    public var unit: Unit? = ._in

    public init(length: Int? = nil, unit: Unit? = ._in) {
        self.length = length
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case length
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

