//
// RelationshipInterest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RelationshipInterest: String, Codable, CaseIterable {
    case dating = "DATING"
    case datingShortTerm = "DATING_SHORT_TERM"
    case datingLongTerm = "DATING_LONG_TERM"
    case friendship = "FRIENDSHIP"
    case collaboration = "COLLABORATION"
}
