//
// Religion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Religion: String, Codable, CaseIterable {
    case agnostic = "AGNOSTIC"
    case atheist = "ATHEIST"
    case buddhist = "BUDDHIST"
    case christian = "CHRISTIAN"
    case hindu = "HINDU"
    case jewish = "JEWISH"
    case muslim = "MUSLIM"
    case other = "OTHER"
    case notDisclosed = "NOT_DISCLOSED"
}
