//
// TimeOfDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * EARLY_MORNING: 3am – 8am * MORNING: 8am – 12pm * AFTERNOON: 12pm – 5pm * EVENING: 5pm – 8pm * NIGHT: 8pm – 3am  */
public enum TimeOfDay: String, Codable, CaseIterable {
    case earlyMorning = "EARLY_MORNING"
    case morning = "MORNING"
    case afternoon = "AFTERNOON"
    case evening = "EVENING"
    case night = "NIGHT"
}
