//
// TroovActivityCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TroovActivityCategory: String, Codable, CaseIterable {
    case culturalExperiences = "CULTURAL_EXPERIENCES"
    case funAndGames = "FUN_AND_GAMES"
    case growthAndCollaboration = "GROWTH_AND_COLLABORATION"
    case indoorEntertainment = "INDOOR_ENTERTAINMENT"
    case outdoorAdventures = "OUTDOOR_ADVENTURES"
    case relaxingEscapes = "RELAXING_ESCAPES"
    case sportsAndFitness = "SPORTS_AND_FITNESS"
    case other = "OTHER"
}
