//
// TroovActivity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines a troov activity */
public struct TroovActivity: Codable, JSONEncodable, Hashable {

    public var category: TroovActivityCategory?
    public var name: String?
    public var emoji: String?

    public init(category: TroovActivityCategory? = nil, name: String? = nil, emoji: String? = nil) {
        self.category = category
        self.name = name
        self.emoji = emoji
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case name
        case emoji
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(emoji, forKey: .emoji)
    }
}

