//
// TroovStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status of the match request:  * CONFIRMED                 | The creator of the troov has approved the match request  * OPEN                      | The troov creator has not confirmed with any other user  * CANCELLED_BY_CREATOR      | The troov creator cancelled this troov  * CANCELLED_BY_REQUESTER    | The requester cancelled this troov  * PENDING_REVIEW            | The troov is completed and pending review  * COMPLETED                 | The troov creator went on a troov and its confirmed via review  * NO_SHOW_BY_CREATOR        | The troov creator did not show up to the date  * NO_SHOW_BY_REQUESTER      | The requester did not show up to the date  * EXPIRED                   | The troov is past start date with no confirmations  */
public enum TroovStatus: String, Codable, CaseIterable {
    case confirmed = "CONFIRMED"
    case _open = "OPEN"
    case cancelledByCreator = "CANCELLED_BY_CREATOR"
    case cancelledByRequester = "CANCELLED_BY_REQUESTER"
    case pendingReview = "PENDING_REVIEW"
    case completed = "COMPLETED"
    case noShowByCreator = "NO_SHOW_BY_CREATOR"
    case noShowByRequester = "NO_SHOW_BY_REQUESTER"
    case expired = "EXPIRED"
}
