//
// VerifySmsCodeForUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** All data related to a User in the application */
public struct VerifySmsCodeForUserRequest: Codable, JSONEncodable, Hashable {

    /** the code that the user received over SMS */
    public var userSubmittedCode: Int?

    public init(userSubmittedCode: Int? = nil) {
        self.userSubmittedCode = userSubmittedCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userSubmittedCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userSubmittedCode, forKey: .userSubmittedCode)
    }
}

